-- drop table if exists answer;
/*create table answer (
  id bigint generated by default as identity,
  title varchar(2000),
  answer varchar(5),
  type int,
  created_at timestamp,
  updated_at timestamp,
  primary key (id)
);*/

drop table if exists t_user;

create table t_user (
    id bigint AUTO_INCREMENT,
    name varchar(2000),
    gender varchar(6),
    primary key(id)
)